apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring 
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashingLoop
      repeatInterval: 10m
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'ilemona02@gmail.com'
      from: 'ilemona02@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'ilemona02@gmail.com'
      authIdentity: 'ilemona02@gmail.com'
      authPassword: 
        name: gmail-auth
        key: password

